/**
 * Markdown → Atlassian Document Format (ADF) converter.
 *
 * Covers all patterns generated by the AI enrichment prompts:
 *   Blocks:   headings (## h2 – ###### h6), fenced code blocks, tables,
 *             bullet lists, ordered lists, task lists (- [ ]/- [x]),
 *             nested lists (2 levels), blockquotes, horizontal rules,
 *             paragraphs
 *   Inline:   **bold**, *italic*, `code`, [link](url), ~~strike~~,
 *             ***bold-italic***
 */

// ── ADF types ─────────────────────────────────────────────────

interface AdfMark {
  type: "strong" | "em" | "code" | "link" | "strike";
  attrs?: { href?: string };
}

interface AdfNode {
  type: string;
  attrs?: Record<string, unknown>;
  content?: AdfNode[];
  text?: string;
  marks?: AdfMark[];
}

// ── Inline parser ─────────────────────────────────────────────

function inlineToAdf(raw: string): AdfNode[] {
  if (!raw) {
    return [];
  }

  const nodes: AdfNode[] = [];
  let s = raw;

  while (s.length > 0) {
    // Bold-italic ***text***
    const bi = /^\*\*\*(.+?)\*\*\*/.exec(s);

    if (bi) {
      nodes.push({ type: "text", text: bi[1], marks: [{ type: "strong" }, { type: "em" }] });
      s = s.slice(bi[0].length);
      continue;
    }

    // Bold **text** or __text__
    const bold = /^\*\*(.+?)\*\*|^__(.+?)__/.exec(s);

    if (bold) {
      nodes.push({ type: "text", text: bold[1] ?? bold[2], marks: [{ type: "strong" }] });
      s = s.slice(bold[0].length);
      continue;
    }

    // Strikethrough ~~text~~
    const strike = /^~~(.+?)~~/.exec(s);

    if (strike) {
      nodes.push({ type: "text", text: strike[1], marks: [{ type: "strike" }] });
      s = s.slice(strike[0].length);
      continue;
    }

    // Italic *text* or _text_
    const em = /^\*(?!\*)(.+?)(?<!\*)\*|^_(?!_)(.+?)(?<!_)_/.exec(s);

    if (em) {
      nodes.push({ type: "text", text: em[1] ?? em[2], marks: [{ type: "em" }] });
      s = s.slice(em[0].length);
      continue;
    }

    // Inline code `text`
    const code = /^`([^`]+)`/.exec(s);

    if (code) {
      nodes.push({ type: "text", text: code[1], marks: [{ type: "code" }] });
      s = s.slice(code[0].length);
      continue;
    }

    // Link [text](url)
    const link = /^\[([^\]]+)\]\(([^)]+)\)/.exec(s);

    if (link) {
      nodes.push({
        type: "text",
        text: link[1],
        marks: [{ type: "link", attrs: { href: link[2] } }],
      });
      s = s.slice(link[0].length);
      continue;
    }

    // Plain text up to next special char
    const plain = /^[^*_`[\]~]+/.exec(s);

    if (plain) {
      nodes.push({ type: "text", text: plain[0] });
      s = s.slice(plain[0].length);
    } else {
      nodes.push({ type: "text", text: s[0] });
      s = s.slice(1);
    }
  }

  return nodes;
}

// ── ID generator for task list nodes ─────────────────────────
let _idCounter = 0;

function nextId(): string {
  return String(++_idCounter);
}

// ── List parsing (handles nesting + task lists) ───────────────

interface ParsedItem {
  text: string;
  indent: number;
  ordered: boolean;
  checked: boolean | null; // null = not a task item
}

function parseRawListItems(lines: string[]): ParsedItem[] {
  return lines.map((line): ParsedItem => {
    const indentMatch = /^(\s*)/.exec(line)!;
    const indent = indentMatch[1].length;

    const taskMatch = /^\s*[-*+]\s+\[([ xX])\]\s+(.*)/.exec(line);

    if (taskMatch) {
      return {
        text: taskMatch[2],
        indent,
        ordered: false,
        checked: taskMatch[1].toLowerCase() === "x",
      };
    }

    const orderedMatch = /^\s*(\d+)\.\s+(.*)/.exec(line);

    if (orderedMatch) {
      return { text: orderedMatch[2], indent, ordered: true, checked: null };
    }

    const bulletMatch = /^\s*[-*+]\s+(.*)/.exec(line);

    if (bulletMatch) {
      return { text: bulletMatch[1], indent, ordered: false, checked: null };
    }

    // Continuation line (wrapped text) — attach to previous
    return { text: line.trim(), indent, ordered: false, checked: null };
  });
}

/** Build nested ADF list from flat ParsedItems starting at a minimum indent level. */
function buildList(
  items: ParsedItem[],
  start: number,
  minIndent: number
): { node: AdfNode; end: number } {
  const isTask = items.slice(start).some((it) => it.checked !== null);
  // eslint-disable-next-line no-nested-ternary
  const listType = isTask ? "taskList" : items[start]?.ordered ? "orderedList" : "bulletList";

  const children: AdfNode[] = [];
  let i = start;

  while (i < items.length && items[i].indent >= minIndent) {
    const item = items[i];

    if (item.indent > minIndent) {
      // Deeper indent — belongs to previous item's sub-list
      if (children.length === 0) {
        i++;
        continue;
      }

      const lastChild = children[children.length - 1];
      const { node: subList, end } = buildList(items, i, item.indent);

      (lastChild.content ??= []).push(subList);
      i = end;
      continue;
    }

    // Same level — new list item
    const itemContent: AdfNode[] = [{ type: "paragraph", content: inlineToAdf(item.text) }];

    if (isTask) {
      children.push({
        type: "taskItem",
        attrs: { localId: nextId(), state: item.checked ? "DONE" : "TODO" },
        content: inlineToAdf(item.text),
      });
    } else {
      const listItem: AdfNode = { type: "listItem", content: itemContent };

      children.push(listItem);
    }

    i++;

    // Check if next item is a sub-list
    if (i < items.length && items[i].indent > minIndent && !isTask) {
      const { node: subList, end } = buildList(items, i, items[i].indent);
      const lastItem = children[children.length - 1];

      (lastItem.content ??= []).push(subList);
      i = end;
    }
  }

  const node: AdfNode = {
    type: listType,
    content: children,
    ...(isTask ? { attrs: { localId: nextId() } } : {}),
  };

  return { node, end: i };
}

// ── Table parser ──────────────────────────────────────────────

function parseTable(lines: string[]): AdfNode | null {
  if (lines.length < 2) {
    return null;
  }

  const parseCells = (line: string): string[] =>
    line
      .replace(/^\||\|$/g, "")
      .split("|")
      .map((c) => c.trim());

  if (!/^\s*\|?\s*[-:]+[-| :]*\s*$/.test(lines[1])) {
    return null;
  }

  const headerRow: AdfNode = {
    type: "tableRow",
    content: parseCells(lines[0]).map((cell) => ({
      type: "tableHeader",
      attrs: { colspan: 1, rowspan: 1 },
      content: [{ type: "paragraph", content: inlineToAdf(cell) }],
    })),
  };

  const bodyRows: AdfNode[] = lines.slice(2).map((line) => ({
    type: "tableRow",
    content: parseCells(line).map((cell) => ({
      type: "tableCell",
      attrs: { colspan: 1, rowspan: 1 },
      content: [{ type: "paragraph", content: inlineToAdf(cell) }],
    })),
  }));

  return {
    type: "table",
    attrs: { isNumberColumnEnabled: false, layout: "default" },
    content: [headerRow, ...bodyRows],
  };
}

// ── Main converter ────────────────────────────────────────────

// eslint-disable-next-line complexity, sonarjs/cognitive-complexity
export function markdownToAdf(markdown: string): {
  version: 1;
  type: "doc";
  content: AdfNode[];
} {
  _idCounter = 0; // reset per document
  const lines = markdown.split("\n");
  const nodes: AdfNode[] = [];
  let i = 0;

  const isListLine = (l: string) => /^\s*[-*+]\s/.test(l) || /^\s*\d+\.\s/.test(l);

  while (i < lines.length) {
    const line = lines[i];

    // Blank line
    if (line.trim() === "") {
      i++;
      continue;
    }

    // Fenced code block
    const fenceStart = /^```(\w*)/.exec(line);

    if (fenceStart) {
      const lang = fenceStart[1] || undefined;
      const codeLines: string[] = [];

      i++;
      while (i < lines.length && !/^```\s*$/.test(lines[i])) {
        codeLines.push(lines[i++]);
      }

      i++; // closing ```
      nodes.push({
        type: "codeBlock",
        attrs: lang ? { language: lang } : {},
        content: [{ type: "text", text: codeLines.join("\n") }],
      });
      continue;
    }

    // Heading
    const heading = /^(#{1,6})\s+(.+)/.exec(line);

    if (heading) {
      nodes.push({
        type: "heading",
        attrs: { level: Math.min(heading[1].length, 6) },
        content: inlineToAdf(heading[2]),
      });
      i++;
      continue;
    }

    // Horizontal rule
    if (/^[-*_]{3,}\s*$/.test(line)) {
      nodes.push({ type: "rule" });
      i++;
      continue;
    }

    // Blockquote
    if (/^>\s?/.test(line)) {
      const quoteLines: string[] = [];

      while (i < lines.length && /^>\s?/.test(lines[i])) {
        quoteLines.push(lines[i].replace(/^>\s?/, ""));
        i++;
      }

      // Recursively convert the inner content
      const inner = markdownToAdf(quoteLines.join("\n"));

      nodes.push({ type: "blockquote", content: inner.content });
      continue;
    }

    // Table
    if (line.includes("|")) {
      const tableLines: string[] = [];

      while (i < lines.length && lines[i].includes("|")) {
        tableLines.push(lines[i++]);
      }

      const table = parseTable(tableLines);

      if (table) {
        nodes.push(table);
      } else {
        for (const tl of tableLines) {
          const content = inlineToAdf(tl);

          if (content.length) {
            nodes.push({ type: "paragraph", content });
          }
        }
      }

      continue;
    }

    // List (bullet, ordered, or task)
    if (isListLine(line)) {
      const listLines: string[] = [];

      // Collect all list lines including indented continuations
      while (i < lines.length && (isListLine(lines[i]) || /^\s{2,}/.test(lines[i]))) {
        // Only add if it looks like a real list line or indented sub-item
        if (isListLine(lines[i]) || (listLines.length > 0 && /^\s{2,}[-*+\d]/.test(lines[i]))) {
          listLines.push(lines[i]);
        } else if (listLines.length > 0 && lines[i].trim() === "") {
          // blank line might end the list
          break;
        }

        i++;
      }

      if (listLines.length > 0) {
        const items = parseRawListItems(listLines);
        const minIndent = Math.min(...items.map((it) => it.indent));
        const { node } = buildList(items, 0, minIndent);

        nodes.push(node);
      }

      continue;
    }

    // Paragraph — collect until a blank line or block-level marker
    const paraLines: string[] = [];

    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !/^#{1,6}\s/.test(lines[i]) &&
      !/^```/.test(lines[i]) &&
      !/^[-*_]{3,}\s*$/.test(lines[i]) &&
      !lines[i].includes("|") &&
      !isListLine(lines[i]) &&
      !/^>/.test(lines[i])
    ) {
      paraLines.push(lines[i++]);
    }

    if (paraLines.length > 0) {
      const content = inlineToAdf(paraLines.join(" "));

      if (content.length) {
        nodes.push({ type: "paragraph", content });
      }
    }
  }

  return {
    version: 1,
    type: "doc",
    content: nodes.length > 0 ? nodes : [{ type: "paragraph", content: [] }],
  };
}
